### ISSUE TITLE
switch backend implementation

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-bezier#6]
backend here is LGPL: would rather avoid that.

**Comment by morganherlocker** [comment]
might be able to try https://github.com/morganherlocker/cubic-spline

Inspired by someone else, who was inspired by wikipedia, so might be even muddier, but I will look into it.

**Comment by tcql** [comment]
BezierSpline [has been updated to MIT license](https://github.com/leszekr/bezier-spline-js/commit/aad9debf86f686b4985461acbdf3e6b00761b423). I updated our citation [here](https://github.com/Turfjs/turf-bezier/commit/800e3dd04ccb581477edf97a913e82ff7a3bd6df)

**Comment by hrieke** [comment]
Just to note that the package.json file states the license as ISC.
While they are nearly the same, the middle part "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." is omitted.
